### ISSUE TITLE
Display domain name for posts

### ISSUE THREAD

**Issue by ferg1e** [ferg1e/peaches-n-stink#12]
If a link was submitted with a post (links are optional), then display the domain name next to the post title.

**Comment by ghost** [comment]
There are two approaches:

1. Simply extract the domain from the url after its retrieved from the database. It would solve this issue but look to number two.
2. Store the domain name in the database itself. This would not only solve this issue, but allow you to do something like https://www.reddit.com/domain/youtube.com/new/ or https://news.ycombinator.com/from?site=bbc.com

**Comment by ferg1e** [comment]
I like the idea of storing the domain name in its own column.

**Comment by ferg1e** [comment]
This is done. Each post has a domain_name_id and there's a new tdomainname table.
