### ISSUE TITLE
What version of node does this support?

### ISSUE THREAD

**Issue by OmgImAlexis** [ferg1e/peaches-n-stink#20]
I'm wanting to open some PRs to switch to using the [nullish coalescing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator) but it requires node 14. Would that be okay?

**Comment by ferg1e** [comment]
I have only tried it on node 10. Should probably upgrade that - maybe I will try it on 14 at some point. Would you like to try it on 14?

**Comment by OmgImAlexis** [comment]
I’m trying it on 17 and it works.

The reason I ask is the lock file changes when moving to newer versions. It might make sense to lock the version of npm down so PRs don’t break things if someone uses a too new npm.

**Comment by ferg1e** [comment]
Nice. I wonder if it all works. It's probably fine as I tried to use simple constructs.
